# Generated by Django 4.2.9 on 2024-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsapp", "0003_favouritestock_delete_favoritestock"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="sentiment_scores",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
